package com.example.ui.theme

enum class AppLanguage(val code: String, val displayName: String, val isRtl: Boolean) {
    ENGLISH("en", "English", false),
    ARABIC("ar", "العربية", true),
    FRENCH("fr", "Français", false)
}

object Localization {
    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.ARABIC -> arabicStrings[key] ?: englishStrings[key] ?: key
            AppLanguage.FRENCH -> frenchStrings[key] ?: englishStrings[key] ?: key
            AppLanguage.ENGLISH -> englishStrings[key] ?: key
        }
    }

    private val englishStrings = mapOf(
        "app_tagline" to "Don't wonder where to go. Discover your next experience.",
        "nav_home" to "Home",
        "nav_explore" to "Explore",
        "nav_surprise" to "Surprise Me",
        "nav_map" to "Map",
        "nav_saved" to "Saved",
        "nav_profile" to "Profile",
        "search_hint" to "Search places, cafes, gaming, vibes...",
        "surprise_me_title" to "Surprise Me 🎲",
        "surprise_me_sub" to "Let WAYGO pick the perfect adventure for you right now",
        "spin_button" to "ROLL THE DICE 🎲",
        "spin_loading" to "Finding your adventure...",
        "ai_concierge_title" to "AI Concierge",
        "ai_concierge_desc" to "Ask me anything (e.g. 2 hours with friends under $20)",
        "recommended_for_you" to "Recommended For You",
        "near_you" to "Near You",
        "popular_now" to "Popular Now",
        "trending" to "Trending Experiences",
        "because_you_like" to "Because You Love",
        "new_places" to "Fresh & New Spots",
        "budget" to "Budget",
        "distance" to "Distance",
        "companions" to "Companions",
        "available_time" to "Available Time",
        "filter_open_now" to "Open Now",
        "filter_indoor" to "Indoor",
        "filter_outdoor" to "Outdoor",
        "filter_top_rated" to "Top Rated",
        "go_there" to "Go There",
        "save" to "Save",
        "saved" to "Saved",
        "share" to "Share",
        "reviews" to "Reviews",
        "write_review" to "Write a Review",
        "add_to_collection" to "Add to Collection",
        "collections" to "Collections",
        "my_world" to "My World",
        "places_discovered" to "Places Discovered",
        "level" to "Level",
        "badges" to "Badges",
        "xp_points" to "XP",
        "onboarding_title_1" to "Discover more around you",
        "onboarding_sub_1" to "Never wonder where to go again. Find experiences made for your vibe.",
        "onboarding_title_2" to "Tell us what you love",
        "onboarding_sub_2" to "Select the activities and spots that spark your excitement.",
        "onboarding_title_3" to "Set your typical budget",
        "onboarding_sub_3" to "From budget-friendly gems to luxury experiences.",
        "onboarding_title_4" to "Experience Discovery",
        "onboarding_sub_4" to "Enable location for real-time magic, weather-aware discovery, and rewards.",
        "get_started" to "Get Started",
        "skip" to "Skip",
        "next" to "Next",
        "level_up" to "LEVEL UP!",
        "badge_unlocked" to "Badge Unlocked!",
        "empty_saved_title" to "Your next favorite place is waiting",
        "empty_saved_sub" to "Tap the heart icon on any place to save it for later.",
        "start_exploring" to "Start Exploring",
        "weather_rainy" to "Rainy outside - prioritizing cozy indoor spots",
        "weather_sunny" to "Sunny vibes - prioritizing outdoor adventures",
        "itinerary_title" to "AI Smart Itinerary",
        "itinerary_desc" to "A custom-timed flow crafted for your group & budget",
        "auth_login" to "Log In",
        "auth_register" to "Create Account",
        "auth_logout" to "Log Out",
        "auth_email" to "Email Address",
        "auth_password" to "Password",
        "auth_name" to "Full Name",
        "auth_username" to "Username",
        "auth_forgot" to "Forgot Password?",
        "auth_delete_account" to "Delete Account & Data",
        "auth_delete_confirm" to "Are you sure you want to delete your account? All your XP, badges, reviews, and saved places will be permanently removed.",
        "delete" to "Delete",
        "cancel" to "Cancel",
        "admin_portal" to "Business Portal & Moderation",
        "admin_reports" to "User Reports",
        "admin_biz" to "Business Claims",
        "claim_business" to "Claim this Business",
        "report_place" to "Report this place",
        "report_review" to "Report review",
        "privacy_policy" to "Privacy Policy",
        "terms_of_service" to "Terms of Service",
        "currency_selector" to "Currency",
        "city_selector" to "Select City / Location",
        "live_search" to "Live Global Search",
        "sponsored" to "Verified Partner",
        "check_in" to "Check In (+50 XP)",
        "checked_in" to "Checked In ✓",
        "helpful" to "Helpful"
    )

    private val arabicStrings = mapOf(
        "app_tagline" to "لا تفكر وين تروح.. اكتشف تجربتك الجاية!",
        "nav_home" to "الرئيسية",
        "nav_explore" to "استكشف",
        "nav_surprise" to "فاجئني",
        "nav_map" to "الخريطة",
        "nav_saved" to "المحفوظات",
        "nav_profile" to "حسابي",
        "search_hint" to "ابحث عن مقاهي، ألعاب، مطاعم، أجواء...",
        "surprise_me_title" to "فاجئني 🎲",
        "surprise_me_sub" to "دع WAYGO يختار لك المغامرة المثالية في ثوانٍ",
        "spin_button" to "ارمِ النرد واكتشف 🎲",
        "spin_loading" to "نبحث لك عن تجربة لا تُنسى...",
        "ai_concierge_title" to "المساعد الذكي",
        "ai_concierge_desc" to "اسألني أي شيء (مثال: ساعتين مع أصحابي بميزانية 20$)",
        "recommended_for_you" to "موصى به لك",
        "near_you" to "بالقرب منك",
        "popular_now" to "الأكثر رواجاً الآن",
        "trending" to "تجارب متصدرة",
        "because_you_like" to "لأنك تفضل",
        "new_places" to "أماكن جديدة وحصرية",
        "budget" to "الميزانية",
        "distance" to "المسافة",
        "companions" to "مع مين؟",
        "available_time" to "الوقت المتاح",
        "filter_open_now" to "مفتوح الآن",
        "filter_indoor" to "داخلي",
        "filter_outdoor" to "في الهواء الطلق",
        "filter_top_rated" to "الأعلى تقييماً",
        "go_there" to "انطلق إلى هناك",
        "save" to "حفظ",
        "saved" to "محفوظ",
        "share" to "مشاركة",
        "reviews" to "التقييمات",
        "write_review" to "أضف تقييمك",
        "add_to_collection" to "إضافة لمجموعة",
        "collections" to "المجموعات",
        "my_world" to "عالمي الاستكشافي",
        "places_discovered" to "أماكن تم استكشافها",
        "level" to "المستوى",
        "badges" to "الأوسمة",
        "xp_points" to "نقاط الخبرة XP",
        "onboarding_title_1" to "اكتشف ما يدور حولك",
        "onboarding_sub_1" to "لا تحتار بعد اليوم وين تروح.. تجارب مخصصة لذوقك.",
        "onboarding_title_2" to "أخبرنا باهتماماتك",
        "onboarding_sub_2" to "اختر النشاطات والمغامرات التي تحبها.",
        "onboarding_title_3" to "حدد ميزانيتك المعتادة",
        "onboarding_sub_3" to "من الأماكن الاقتصادية الرائعة إلى التجارب الفاخرة.",
        "onboarding_title_4" to "استكشاف فوري وذكي",
        "onboarding_sub_4" to "فعل الموقع لاكتشاف سحري مبني على الطقس ومكافآت مستمرة.",
        "get_started" to "ابدأ الآن",
        "skip" to "تخطي",
        "next" to "التالي",
        "level_up" to "ترقية المستوى!",
        "badge_unlocked" to "وسام جديد تم فتحه!",
        "empty_saved_title" to "مكانك المفضل القادم بانتظارك",
        "empty_saved_sub" to "اضغط على القلب لحفظ أي مكان واستكشافه لاحقاً.",
        "start_exploring" to "ابدأ الاستكشاف",
        "weather_rainy" to "الجو ماطر - نقترح أماكن مغلقة دافئة",
        "weather_sunny" to "الجو رائع - نقترح أنشطة وأماكن خارجية",
        "itinerary_title" to "جدول رحلة ذكي بالذكاء الاصطناعي",
        "itinerary_desc" to "خطة متكاملة ومحسوبة الوقت والميزانية لمجموعتك",
        "auth_login" to "تسجيل الدخول",
        "auth_register" to "إنشاء حساب جديد",
        "auth_logout" to "تسجيل الخروج",
        "auth_email" to "البريد الإلكتروني",
        "auth_password" to "كلمة المرور",
        "auth_name" to "الاسم الكامل",
        "auth_username" to "اسم المستخدم",
        "auth_forgot" to "نسيت كلمة المرور؟",
        "auth_delete_account" to "حذف الحساب والبيانات",
        "auth_delete_confirm" to "هل أنت متأكد من رغبتك بحذف حسابك نهائياً؟ سيتم مسح جميع نقاط الخبرة والأوسمة والتقييمات بشكل كامل.",
        "delete" to "حذف",
        "cancel" to "إلغاء",
        "admin_portal" to "بوابة الأعمال والإشراف",
        "admin_reports" to "بلاغات المستخدمين",
        "admin_biz" to "توثيق الأنشطة التجارية",
        "claim_business" to "طلب ملكية هذا النشاط",
        "report_place" to "الإبلاغ عن هذا المكان",
        "report_review" to "الإبلاغ عن التقييم",
        "privacy_policy" to "سياسة الخصوصية",
        "terms_of_service" to "شروط الخدمة",
        "currency_selector" to "العملة",
        "city_selector" to "اختر المدينة / الموقع",
        "live_search" to "بحث جغرافي حي",
        "sponsored" to "شريك موثق",
        "check_in" to "تسجيل حضور (+50 XP)",
        "checked_in" to "تم تسجيل الزيارة ✓",
        "helpful" to "مفيد"
    )

    private val frenchStrings = mapOf(
        "app_tagline" to "Ne cherchez plus où aller. Découvrez votre prochaine aventure.",
        "nav_home" to "Accueil",
        "nav_explore" to "Explorer",
        "nav_surprise" to "Surprise",
        "nav_map" to "Carte",
        "nav_saved" to "Favoris",
        "nav_profile" to "Profil",
        "search_hint" to "Cafés, jeux, restaurants, ambiances...",
        "surprise_me_title" to "Surprenez-moi 🎲",
        "surprise_me_sub" to "Laissez WAYGO choisir l'expérience parfaite pour vous",
        "spin_button" to "LANCER LE DÉ 🎲",
        "spin_loading" to "Recherche de votre aventure...",
        "ai_concierge_title" to "Concierge IA",
        "ai_concierge_desc" to "Demandez n'importe quoi (ex: 2h entre amis avec 20$)",
        "recommended_for_you" to "Recommandé Pour Vous",
        "near_you" to "Près de Vous",
        "popular_now" to "Populaire en ce Moment",
        "trending" to "Tendances",
        "because_you_like" to "Parce que vous aimez",
        "new_places" to "Nouveautés",
        "budget" to "Budget",
        "distance" to "Distance",
        "companions" to "Accompagnants",
        "available_time" to "Temps Disponible",
        "filter_open_now" to "Ouvert",
        "filter_indoor" to "Intérieur",
        "filter_outdoor" to "Extérieur",
        "filter_top_rated" to "Mieux Notés",
        "go_there" to "Y aller",
        "save" to "Sauvegarder",
        "saved" to "Enregistré",
        "share" to "Partager",
        "reviews" to "Avis",
        "write_review" to "Donner un avis",
        "add_to_collection" to "Ajouter à une collection",
        "collections" to "Collections",
        "my_world" to "Mon Monde",
        "places_discovered" to "Lieux Découverts",
        "level" to "Niveau",
        "badges" to "Badges",
        "xp_points" to "XP",
        "onboarding_title_1" to "Découvrez autour de vous",
        "onboarding_sub_1" to "Ne vous demandez plus où sortir. Des expériences taillées pour vous.",
        "onboarding_title_2" to "Ce que vous aimez",
        "onboarding_sub_2" to "Sélectionnez les activités qui vous inspirent.",
        "onboarding_title_3" to "Votre budget habituel",
        "onboarding_sub_3" to "Des pépites abordables aux sorties premium.",
        "onboarding_title_4" to "Découverte Magique",
        "onboarding_sub_4" to "Activez la localisation pour des recommandations intelligentes.",
        "get_started" to "Commencer",
        "skip" to "Passer",
        "next" to "Suivant",
        "level_up" to "NIVEAU SUPÉRIEUR !",
        "badge_unlocked" to "Nouveau Badge Débloqué !",
        "empty_saved_title" to "Votre prochain coup de cœur vous attend",
        "empty_saved_sub" to "Touchez le cœur pour enregistrer vos lieux favoris.",
        "start_exploring" to "Commencer à explorer",
        "weather_rainy" to "Pluvieux - focus sur des lieux chaleureux à l'intérieur",
        "weather_sunny" to "Beau temps - activités de plein air recommandées",
        "itinerary_title" to "Itinéraire Intelligent IA",
        "itinerary_desc" to "Programme optimisé en temps et budget pour votre groupe",
        "auth_login" to "Connexion",
        "auth_register" to "Créer un compte",
        "auth_logout" to "Se déconnecter",
        "auth_email" to "Adresse e-mail",
        "auth_password" to "Mot de passe",
        "auth_name" to "Nom complet",
        "auth_username" to "Nom d'utilisateur",
        "auth_forgot" to "Mot de passe oublié ?",
        "auth_delete_account" to "Supprimer le compte et les données",
        "auth_delete_confirm" to "Êtes-vous sûr de vouloir supprimer définitivement votre compte ? Tous vos points XP, badges et avis seront effacés.",
        "delete" to "Supprimer",
        "cancel" to "Annuler",
        "admin_portal" to "Portail Entreprises & Modération",
        "admin_reports" to "Signalements",
        "admin_biz" to "Revendications",
        "claim_business" to "Revendiquer cet établissement",
        "report_place" to "Signaler ce lieu",
        "report_review" to "Signaler cet avis",
        "privacy_policy" to "Politique de Confidentialité",
        "terms_of_service" to "Conditions d'Utilisation",
        "currency_selector" to "Devise",
        "city_selector" to "Sélectionner la ville / Région",
        "live_search" to "Recherche globale en direct",
        "sponsored" to "Partenaire Vérifié",
        "check_in" to "Enregistrer ma visite (+50 XP)",
        "checked_in" to "Visite confirmée ✓",
        "helpful" to "Utile"
    )
}
